[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "googletrans>=3.0.0",
    "openpyxl>=3.1.5",
    "pytelegrambotapi>=4.25.0",
    "requests>=2.32.3",
    "telegram>=0.0.1",
]
